version: "3"

services:
  db:
    image: mysql:9.5.0 # It's better to specify the version you were using
    container_name: db-go-tweets
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=go_tweets
    volumes:
      - ./mysql_data:/var/lib/mysql

